version: '3.8'

services:
  node:
    build:
      context: ./scorm-dp
      dockerfile: Dockerfile
    container_name: scorm-dp
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=scormdb
      - SCORM_APP_ID=appid
      - SCORM_SECRET_KEY=secretkey
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=scormdb
    ports:
      - "3306:3306"
    volumes:
#      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

#volumes:
#  mysql-data: